# Generated by Django 4.1.7 on 2023-02-20 14:45

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], default='profile_pics/default.png', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[300, 300], upload_to='profile_pics'),
        ),
    ]
